### ISSUE TITLE
DT2 and DT3 missing

### ISSUE THREAD

**Issue by zertrin** [cheeaun/railrouter-sg#1]
Hi, thanks for this service.

I noticed that DT2 Cashew and DT3 Hillview stations on the Downtown line are missing, even after refreshing or zooming many times:

![image](https://user-images.githubusercontent.com/1447163/30306166-4f2c7760-97a9-11e7-9be0-95ef29bc99bc.png)

**Comment by cheeaun** [comment]
Interestingly, both of the MRT stations were accidentally(?) removed from the DTL line in OpenStreetMap 😰 http://www.openstreetmap.org/relation/2313458/history

I've added a commentary here http://www.openstreetmap.org/changeset/45993309 (7-month-old change).

If this is not fixed, I'll need to find another source of data.

**Comment by zertrin** [comment]
I have fixed it in this changeset: http://www.openstreetmap.org/changeset/52108463#map=17/1.36609/103.76579&layers=H
